version: '3.5'

networks:
    appnet:
        driver: bridge

services:
    webapp:
        image: a191f62c39bd
        ports:
            - "8000:8000"
        networks:
            - appnet
        volumes:

            - /home/shuddhatm/Video-conferencing-too-using-WebRTC/:/home/WebRTC

    redis:
        image: redis:5
        networks:
            - appnet
